syntax on


"  plugin indenting on
"autocmd filetype gitcommit textwidth=72

" Auto-wrap git commit messages at 72 characters
au FileType gitcommit setlocal tw=72

" number of visual spaces per TAB
set tabstop=2

" number of spaces in tab when editing
set softtabstop=2

" tabs are spaces
set expandtab

" ### UI ###
set number " show line numbers
set showcmd " Show command in bottom bar
set wildmenu " visual autocomplete for command menu
set showmatch " highlight matching [{()}]

" ### Searching ###

" Fix backspace behavior to make it work consistently
set bs=2
